version: "3.7"
services:
  db:
    image: postgres:15
    container_name: db_app
    command: -p 1221
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 1221
    env_file:
      - .env-non-dev

  redis:
    image: redis:7
    container_name: redis_app
    command: redis-server --port 5370
    volumes:
      - redis_data:/usr/local/etc/redis
    expose:
        - 5370


  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: fastapi_app
    command: ["/fastapi_app/docker/app.sh"]
    volumes:
      - my_content:/fastapi_app/media
    ports:
      - 9999:8000
    depends_on:
      - db
      - redis

  celery:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: celery_app
    command: ["/fastapi_app/docker/celery.sh","celery"]
    volumes:
      - my_content:/fastapi_app/media:ro
    depends_on:
      - redis

  flower:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: flower_app
    command: ["/fastapi_app/docker/celery.sh","flower"]
    depends_on:
      - redis
      - celery
    ports:
      - 8888:5555

volumes:
  my_content:
  postgres_data:
  redis_data:
