"""Items model update

Revision ID: 1ae80e2d538b
Revises: 7be6e57478d2
Create Date: 2023-08-26 18:29:06.301693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ae80e2d538b'
down_revision: Union[str, None] = '7be6e57478d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('audio_note', sa.String(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'audio_note')
    # ### end Alembic commands ###
