"""Update item model

Revision ID: 7b3a5d46bb56
Revises: 71a82776788a
Create Date: 2023-09-09 15:39:14.840951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b3a5d46bb56'
down_revision: Union[str, None] = '71a82776788a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'audio_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'audio_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
