"""Meeting model

Revision ID: b1fec6ffee8b
Revises: d54cee2d1d61
Create Date: 2023-10-01 00:12:00.801367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1fec6ffee8b'
down_revision: Union[str, None] = 'd54cee2d1d61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('item', sa.Column('meeting_id', sa.Integer(), nullable=False))
    op.drop_constraint('item_user_id_fkey', 'item', type_='foreignkey')
    op.create_foreign_key(None, 'item', 'meeting', ['meeting_id'], ['id'], ondelete='cascade')
    op.drop_column('item', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.create_foreign_key('item_user_id_fkey', 'item', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('item', 'meeting_id')
    op.drop_table('meeting')
    # ### end Alembic commands ###
