"""Models update

Revision ID: be55131410c1
Revises: 7ca0d2ed30ca
Create Date: 2023-09-10 00:14:30.328828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be55131410c1'
down_revision: Union[str, None] = '7ca0d2ed30ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('items_audio_id_fkey', 'items', type_='foreignkey')
    op.create_foreign_key(None, 'items', 'user', ['user_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'items', 'audiorecords', ['audio_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.create_foreign_key('items_audio_id_fkey', 'items', 'audiorecords', ['audio_id'], ['id'])
    op.drop_column('items', 'user_id')
    # ### end Alembic commands ###
