"""Models update 8

Revision ID: d54cee2d1d61
Revises: f8a57fa48228
Create Date: 2023-09-10 22:32:46.360886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd54cee2d1d61'
down_revision: Union[str, None] = 'f8a57fa48228'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audiorecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('audio_note', sa.String(length=1000), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_name')
    )
    op.drop_table('items')
    op.drop_table('audiorecords')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audiorecords',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('audiorecords_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('audio_note', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='audiorecords_pkey'),
    sa.UniqueConstraint('file_name', name='audiorecords_file_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('create_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('audio_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['audio_id'], ['audiorecords.id'], name='items_audio_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='items_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='items_pkey')
    )
    op.drop_table('audiorecord')
    op.drop_table('item')
    # ### end Alembic commands ###
